"""
Module containing all macros corresponding to every key

The Macro object stores the function you want to call every time the macro is used, 
as well as its args and kwargs.
"""

from py_macro.macro import Macro



MACROS = {
    "escape": Macro(),
    "F1": Macro(),
    "F2": Macro(),
    "F3": Macro(),
    "F4": Macro(),
    "F5": Macro(),
    "F6": Macro(),
    "F7": Macro(),
    "F8": Macro(),
    "F9": Macro(),
    "F10": Macro(),
    "F11": Macro(),
    "F12": Macro(),
    "1": Macro(),
    "2": Macro(),
    "3": Macro(),
    "4": Macro(),
    "5": Macro(),
    "6": Macro(),
    "7": Macro(),
    "8": Macro(),
    "9": Macro(),
    "0": Macro(),
    "q": Macro(),
    "w": Macro(),
    "e": Macro(),
    "r": Macro(),
    "t": Macro(),
    "y": Macro(),
    "u": Macro(),
    "i": Macro(),
    "o": Macro(),
    "p": Macro(),
    "a": Macro(),
    "s": Macro(),
    "d": Macro(),
    "f": Macro(),
    "g": Macro(),
    "h": Macro(),
    "j": Macro(),
    "k": Macro(),
    "l": Macro(),
    "z": Macro(),
    "x": Macro(),
    "c": Macro(),
    "v": Macro(),
    "b": Macro(),
    "n": Macro(),
    "m": Macro(),
    "space": Macro(),
    "tab": Macro(),
    "capslock": Macro(),
    "rShift": Macro(),
    "rCtrl": Macro(),
    "backspace": Macro(),
    "enter": Macro(),
    "insert": Macro(),
    "home": Macro(),
    "pageup": Macro(),
    "delete": Macro(),
    "end": Macro(),
    "pagedown": Macro(),
    "`": Macro(),
    "minus": Macro(),
    "equals": Macro(),
    "leftbracket": Macro(),
    "rightbracket": Macro(),
    "singlequote": Macro(),
    "semicolon": Macro(),
    "backslash": Macro(),
    "comma": Macro(),
    "period": Macro(),
    "slash": Macro(),
    "numDiv": Macro(),
    "numMult": Macro(),
    "numMinus": Macro(),
    "numPlus": Macro(),
    "numLock": Macro(),
    "numDelete": Macro(),
    "num0": Macro(),
    "num1": Macro(),
    "num2": Macro(),
    "num3": Macro(),
    "num4": Macro(),
    "num5": Macro(),
    "num6": Macro(),
    "num7": Macro(),
    "num8": Macro(),
    "num9": Macro(),
    "up": Macro(),
    "down": Macro(),
    "left": Macro(),
    "right": Macro(),
}
